name: maria_reg2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - bzip2
  - ca-certificates
  - contourpy
  - cuda-nvrtc=12.5
  - cuda-version=12.5
  - cupy=13.2
  - cupy-core=13.2
  - cycler
  - expat
  - fastrlock
  - fonttools
  - joblib
  - kiwisolver
  - kneed
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libcublas
  - libcufft
  - libcurand
  - libcusolver
  - libcusparse
  - libexpat
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - liblapack
  - libnsl
  - libnvjitlink
  - libopenblas
  - libsqlite
  - libstdcxx-ng
  - libuuid
  - libxcrypt
  - libzlib
  - llvmlite
  - matplotlib
  - ncurses
  - numba
  - numpy
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  - pyparsing
  - python-dateutil
  - python_abi
  - pytz
  - readline
  - scipy=1.12
  - seaborn
  - setuptools
  - six
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - contourpy
      - fonttools
      - joblib
      - kiwisolver
      - kneed
      - llvmlite
      - matplotlib
      - numba
      - numpy
      - packaging
      - pandas
      - pillow
      - python-dateutil
      - pytz
      - scipy==1.12
      - seaborn 
      - scikit-learn 
      - statsmodels
