
import pickle
import subprocess
from scipy.integrate import quad as I
from joblib import Parallel, delayed
import math
from .graphpoint import GraphPointAbstract as GPA
from . import graphpoint as graphpoint
import numpy as np
from scipy.optimize import curve_fit
import warnings
import pkgutil
warnings.filterwarnings("ignore")

wfes_single = '/home/weghorn/hali/wfes2/bin/wfes_single'
e = lambda x: math.exp(x)
log10 = lambda x: np.log10(x) if x > 0 else 0

class Predictor():

    def __init__(self):
        self.stiching_point = 10**4
        self.per_pop_linear_regression = {}
        self.self_train()

    def self_train(self):
        '''train the predictor on the points generated by the predictor
        '''
        data = pkgutil.get_data(__name__, "predictor_regression_training_points.pkl")

        try: self.per_pop_linear_regression = pickle.loads(pkgutil.get_data(__name__, "per_pop_linear_regression.pkl"))
        #try: points = pickle.load(open(f"predictor_regression_training_points.pkl", "rb"))
        except Exception as e:
            print(e)
            print('training')
            points = self.get_train_points(popsize_range=[100000,100000], selection_coeff_range=[0, 0])
            #points.extend(self.get_train_points(negative=False))
            self.fit_per_selection_linear_regression(points)

    def get_train_points(self, num=100, popsize_range=[4, 500000], negative=True, selection_coeff_range=[0.0001, 0.000001]):
        points = []
        muxpop_range = [0.0001, 0.1]
        selection_coeff_range = [math.log10(s) if s != 0 else 0 for s in selection_coeff_range]
        train_points = []
        for i, muxpop in enumerate(np.linspace(math.log10(muxpop_range[0]), math.log10(muxpop_range[1]), int(math.sqrt(num)))):
            #print(f'---{i}---', end='\r')
            for popsize in np.linspace(popsize_range[0], popsize_range[1], int(math.sqrt(num))):
                muxpop_ = math.pow(10, muxpop)
                mue_frwrd = muxpop_/popsize
                pop_size = popsize

                point = GPA(mue_frwrd, 0, pop_size, selection_coeff=0)
                #point.mean_sub_rate = self.get_sub_rate_diffusion(point)
                points.append(point)

                if selection_coeff_range == [0,0]: continue
                for selection_coeff in np.linspace(selection_coeff_range[0], selection_coeff_range[1], int(math.sqrt(num))):
                    selection_coeff = math.pow(10, selection_coeff) if selection_coeff != 0 else 0
                    if negative: selection_coeff *= -1

                    try:
                        point = GPA(mue_frwrd, 0, pop_size, selection_coeff=selection_coeff)
                        #mean_sub_rate = self.get_sub_rate_diffusion(point)

                        #if mean_sub_rate == np.inf: continue

                        #point.mean_sub_rate = mean_sub_rate
                        points.append(point)
                    except Exception as e:
                        pass
        def sub_rate(point):
            sub = self.get_sub_rate(point)
            if sub == np.inf: return None
            point.mean_sub_rate = sub
            return point

        points = Parallel(n_jobs=-1, verbose=0)(delayed(sub_rate)(point) for point in points)
        points = [point for point in points if point is not None]


        return points

    def fit_per_selection_linear_regression(self, points):
        '''fit a linear regression for each selection coefficient
        '''
        per_selection_points = {}
        pops = [point.pop_size for point in points]
        for pop in pops:
            per_pop_points = {}
            inner_points = [point for point in points if point.pop_size == pop]

            per_selection_points = {}
            for point in inner_points:
                if point.selection_coeff not in per_selection_points:
                    per_selection_points[point.selection_coeff] = []
                per_selection_points[point.selection_coeff].append(point)

            if pop not in per_pop_points: per_pop_points[pop] = {}
            per_pop_points[pop] = per_selection_points

            self.per_pop_linear_regression[pop] = {s: self._fit_linear_regression(per_selection_points[s]) for s in per_selection_points.keys()}
            pickle.dump(self.per_pop_linear_regression, open(f"per_pop_linear_regression.pkl", "wb"))

    def _fit_linear_regression(self, points):
        xs = np.array([np.log10(point.mue_frwrd) for point in points])
        ys = np.array([np.log10(point.mean_sub_rate) for point in points])

        def linear(x, a, b):
            return a*x + b

        popt, pcov = curve_fit(linear, xs, ys)
        return popt

    def get_sub_rate(self, point):

        #if point.mue_frwrd * point.pop_size <= 0.001:
        if point.mue_frwrd * point.pop_size <= 0.00001 and point.pop_size > self.stiching_point:
            #print('regression')
            return self.get_sub_rate_regression(point)

        if point.pop_size < self.stiching_point:
            return self.get_sub_rate_exact(point)
        else:
            try:
                return self.get_sub_rate_diffusion(point)
            except Exception as e:
                return np.inf

    def get_sub_rate_regression(self, point, interpolate=True, test=False):
        '''get the sub rate using the linear regression
        '''
        def regression_sub(point, selection=None):
            if selection is None: selection = point.selection_coeff
            a, b = per_selection_linear_regression[selection]
            log_subrate = a*np.log10(point.mue_frwrd) + b
            return 10**log_subrate

        if not self.per_pop_linear_regression:
            raise Exception('fit the linear regression first')

        if point.pop_size not in self.per_pop_linear_regression:
            extra_points = self.get_train_points(num=20, popsize_range=[point.pop_size, point.pop_size], negative=False)
            self.fit_per_selection_linear_regression(extra_points)

        per_selection_linear_regression = self.per_pop_linear_regression[point.pop_size]

        def regression_sub(point, selection=None):
            if selection is None: selection = point.selection_coeff
            a, b = per_selection_linear_regression[selection]
            log_subrate = a*np.log10(point.mue_frwrd) + b
            return 10**log_subrate

        selections = [float(x) for x in per_selection_linear_regression.keys()]

        if test and point.selection_coeff in selections:
            #remove the point from the list
            selections.remove(point.selection_coeff)

        if point.selection_coeff < min(selections): return 0
        elif point.selection_coeff > max(selections): return regression_sub(point, max(selections))
        elif point.selection_coeff in selections: return regression_sub(point)

        if point.selection_coeff not in selections:

            if not interpolate:
                min_diff = np.inf
                for selection in selections:
                    if abs(selection - point.selection_coeff) < min_diff:
                        min_diff = abs(selection - point.selection_coeff)
                        most_similar_selection = selection
                return regression_sub(point, most_similar_selection)

            if point.selection_coeff <= min(selections):
                return regression_sub(point, min(selections))

            elif point.selection_coeff >= max(selections):
                return regression_sub(point, max(selections))

            upper = min([x for x in selections if x > point.selection_coeff])
            lower = max([x for x in selections if x < point.selection_coeff])


            subh = np.log10(regression_sub(point, upper))
            subl = np.log10(regression_sub(point, lower))

            #y = y1 + (x-x1)*(y2-y1)/(x2-x1)
            value = subl + (point.selection_coeff - lower)*(subh-subl)/(upper-lower)

            return 10**value

    def get_mu(self, point, ratio=0, **kwargs):

        def inner_func(mu):
            if ratio == 0 and point.mue_bckwrds is not None:
                mu_b = point.mue_bckwrds
            else:
                mu_b = mu/ratio
            return self.get_sub_rate(GPA(mu, mu_b, pop_size=point.pop_size,
                                        selection_coeff=point.selection_coeff))

        #@np.vectorize
        def error(mu, approx=True):
            if ratio == 0 and point.mue_bckwrds is not None:
                mu_b = point.mue_bckwrds
            else:
                mu_b = mu/ratio

            if approx:
                expected_sub_rate = self.get_sub_rate(GPA(mu, mu_b, pop_size=point.pop_size,
                                                        selection_coeff=point.selection_coeff))
            else:
                expected_sub_rate = self.get_sub_rate_diffusion(GPA(mu, mu_b, pop_size=point.pop_size,
                                                          selection_coeff=point.selection_coeff))

            if expected_sub_rate is None: return np.inf
            '''if log10(expected_sub_rate / sub_rate) < -100:
                bla = 1'''
            e = abs(expected_sub_rate - point.mean_sub_rate)
            #e = np.log10(expected_sub_rate) / np.log10(point.mean_sub_rate)
            #e = abs(1-e)
            #if e == 1: return np.inf
            #if np.isnan(e): return np.inf
            return e
            #return (self.get_sub_rate(GPA(mu, mu*ratio, pop_size, selection)) - sub_rate)**2

        l_boundary = point.mean_sub_rate/100
        r_boundary = point.mean_sub_rate*100
        #res = self.minimize_by_search(error, [l_boundary,r_boundary], negative=False, max_depth=10, **kwargs)
        try:
            res = self.binary_search(inner_func, [l_boundary,r_boundary], point.mean_sub_rate, negative=False, max_depth=40, tol=10**-15, **kwargs)
        except Exception as e:
            #print(e)
            #print('trying again by grid search')
            minimize = lambda x: error(x)
            res, _ys = self.minimize_by_search(minimize, [point.mean_sub_rate/100,point.mean_sub_rate*100], negative=False, max_depth=25, silent=True,
                                          tol=10**-15, parallel=False, **kwargs)

        #res = self.minimize_by_search(error, [res*0.9,res*1.1], negative=False, approx=False, **kwargs)
        if (error(res)) > 10**-10:
            if point.pop_size > 1000:
                print(f'pop: {point.pop_size}, selection: {point.selection_coeff}, error: {error(res)} mu: {res}')
                print(f'sub_rate: {point.mean_sub_rate}, calculated: {self.get_sub_rate(GPA(res, point.mue_bckwrds, point.pop_size, point.selection_coeff))}')
                raise Exception('did not converge')

        return res

    def get_sub_rate_exact(self, point):
        '''command format: wfes_single --fixation -N [pop_size] -s [selection_coeff] -v [mue_frwrd] -u [mue_bckwrds] -h 0.5
        '''
        command = f'{wfes_single} --fixation -N {point.pop_size} -s {point.selection_coeff*2} \
                    -v {point.mue_frwrd} -u {point.mue_bckwrds} -h 0.5'

        process = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        output = output.decode()
        lines = output.split('\n')
        time = np.inf
        for line in lines:
            if 'T_fix' in line:
                time = float(line.split('=')[1].strip())
        if time == np.inf:
            return np.inf
        return 1/(time)

    def get_sub_rate_diffusion(self, point):
        #warnings.filterwarnings("error")

        def g_of_x_y(y, sigma, u1, u2):
            #num = 2*I(lambda x: e(-2*sigma*x)*(x**(-2*u1))*((1-x)**(-2*u2)), y, 1, limit=20, epsabs=1e-3, epsrel=1e-3)[0]
            num = 2*I(lambda x: e(-2*sigma*x)*(x**(-2*u1))*((1-x)**(-2*u2)), y, 1)[0]
            #num = 2*II(lambda x: e(-2*sigma*x)*(x**(-2*u1))*((1-x)**(-2*u2)), [y, 1])
            den = y*(1-y) * e(-2*sigma*y)
            den *= (y**(-2*u1))*((1-y)**(-2*u2))
            return num/den

        sigma = 2*point.pop_size*point.selection_coeff
        u1 = point.mue_frwrd*point.pop_size
        u2 = point.mue_bckwrds*point.pop_size
        #time = I(lambda y: g_of_x_y(y, sigma, u1, u2), 0, 1, limit=20, epsabs=1e-3, epsrel=1e-3)[0]
        time = I(lambda y: g_of_x_y(y, sigma, u1, u2), 0, 1)[0]
        #time = float(II(lambda y: g_of_x_y(y, sigma, u1, u2), [0, 1]))
        return (1/time)/point.pop_size

    def get_selection(self, sub_rate, mu, pop_size, ratio=1, l_boundary=1e-4, r_boundary=1e-6, negative=True):
        '''gradient descent to find the selection that gives the sub_rate
        '''

        @np.vectorize
        def error(selection):
            expected_sub_rate = self.get_sub_rate(GPA(mu, mu*ratio, pop_size, selection))
            if expected_sub_rate is None: return np.inf
            '''if log10(expected_sub_rate / sub_rate) < -100:
                bla = 1'''
            e = expected_sub_rate / sub_rate
            e = abs(1-e)
            if e == 1: return np.inf
            return e
            #return (self.get_sub_rate(GPA(mu, mu*ratio, pop_size, selection)) - sub_rate)**2

        res = self.minimize_by_search(error, [l_boundary,r_boundary], negative=negative)
        return res

    def binary_search(self, func, bounds, search_parameter,
                      tol=10**-10, depth=0, negative=True,
                      max_depth=25, log=True, left=None, right=None, **kwargs):

        if depth == 0:
            left = func(bounds[0], **kwargs) if not negative else func(-bounds[0], **kwargs)
            right = func(bounds[1], **kwargs) if not negative else func(-bounds[1], **kwargs)

        middle = (bounds[0] + bounds[1])/2 if not log else 10**((log10(bounds[0]) + log10(bounds[1]))/2)
        middle = -middle if negative else middle
        middle_value = func(middle, **kwargs)
        if abs(middle_value - search_parameter) <= tol:
            return middle

        if depth > max_depth:
            #print('did not converge, minimum error is', abs(middle_value - search_parameter))
            raise Exception('did not converge')
            return middle
        if left< search_parameter < middle_value:
            return self.binary_search(func, [bounds[0], abs(middle)], search_parameter, tol=tol,
                                      depth=depth+1, negative=negative, max_depth=max_depth,
                                      log=log, left=left, right=middle_value, **kwargs)
        elif middle_value < search_parameter < right:
            return self.binary_search(func, [abs(middle), bounds[1]], search_parameter, tol=tol,
                                      depth=depth+1, negative=negative, max_depth=max_depth,
                                      log=log, left=middle_value, right=right, **kwargs)
        else:
            #print('did not converge, minimum error is', abs(middle_value - search_parameter))
            raise Exception('did not converge')
            return middle

    def minimize_by_search(self, func, bounds, tol=10**-10,
                           depth=0, negative=True, breadth=10, first_breadth=None,
                           max_depth=25, nearest_value_tie_breaker=None,
                           log=True, parallel=True,previuos_results={},
                           precesion=0, old_xs=[], old_ys=[],silent=False,**kwargs):
        ''' tolerance is the minimum error that is acceptable
            precesion is the acceptable difference between the bounds

            returns the x that gives the minimum y, and all the computed points
        '''
        def inner_func(x, **kwargs):
            if x in previuos_results:
                return previuos_results[x]
            else:
                return func(x, **kwargs)

        inner_breadth = breadth
        if (depth == 0) and first_breadth is not None: inner_breadth = first_breadth

        if parallel: parallel=-1
        else: parallel=1
        if log:
            xs = np.linspace(log10(abs(bounds[0])), log10(abs(bounds[1])), inner_breadth)
            xs = 10**xs
        else:
            xs = np.linspace(abs(bounds[0]), abs(bounds[1]), inner_breadth)
        if negative: xs = -xs

        xs = np.array([x for x in xs if not np.isnan(x)])
        xs = sorted(xs)

        ys = Parallel(n_jobs=parallel, verbose=0)(delayed(inner_func)(x, **kwargs) for x in xs)
        previuos_results = {x:y for x,y in zip(xs, ys)}
        #ys = [func(x, **kwargs) for x in xs]
        #check if there is more than one minimum
        if nearest_value_tie_breaker is not None:
            minimas = [i for i in range(len(ys)) if ys[i] == min(ys)]
            minimum_i = minimas[np.argmin([abs(xs[i]-nearest_value_tie_breaker) for i in minimas])]
            x = xs[minimum_i]

        else:
            x = xs[np.argmin(ys)]
            minimum_i = np.argmin(ys)

        old_xs.extend(xs)
        old_ys.extend(ys)

        if min(ys) <= tol:
            return x, [old_xs, old_ys]
        if abs(abs(min(xs)) - abs(max(xs))) <= precesion:
            return x, [old_xs, old_ys]
        if len(set(ys)) == 1:
            return x, [old_xs, old_ys]
        if depth > max_depth:
            return x, [old_xs, old_ys]

        if minimum_i == 0:
            l_boundary = xs[0]
            r_boundary = xs[1]
        else:
            new_lower = minimum_i - 1 if minimum_i - 1 >= 0 else 0
            new_upper = minimum_i + 1 if minimum_i + 1 < len(xs) else - 1
            l_boundary = xs[new_lower]
            r_boundary = xs[new_upper]
        if not silent: print('Searching between l_boundary:', l_boundary, 'r_boundary:', r_boundary)
        return self.minimize_by_search(func, [l_boundary, r_boundary], tol, depth=depth+1,
                                       negative=negative, breadth=breadth, max_depth=max_depth,
                                       nearest_value_tie_breaker=nearest_value_tie_breaker,
                                       parallel=parallel, log=log,
                                       previuos_results=previuos_results,
                                       precesion=precesion, old_xs=old_xs, old_ys=old_ys,
                                       silent=silent,**kwargs)
