
import pickle
import subprocess
from scipy.integrate import quad as I
from joblib import Parallel, delayed
import math
from .graphpoint import GraphPointAbstract as GPA
from . import graphpoint as graphpoint
import numpy as np
from scipy.optimize import curve_fit
import warnings
import pkgutil

#maria add ons 
from scipy.optimize import root_scalar
from scipy.optimize import root
from scipy.special import betainc,beta
warnings.filterwarnings("ignore")

BASES=["A", "C", "G", "T"]
wfes_single = '/home/dweghorngroup/packages/wfes2/bin/wfes_single'
e = lambda x: math.exp(x)
log10 = lambda x: np.log10(x) if x > 0 else 0

class Predictor():

    def __init__(self):
        self.stiching_point = 10**4
        self.per_pop_linear_regression = {}
        self.self_train()

    def self_train(self):
        '''train the predictor on the points generated by the predictor
        '''
        data = pkgutil.get_data(__name__, "predictor_regression_training_points.pkl")

        try: self.per_pop_linear_regression = pickle.loads(pkgutil.get_data(__name__, "per_pop_linear_regression.pkl"))
        #try: points = pickle.load(open(f"predictor_regression_training_points.pkl", "rb"))
        except Exception as e:
            print(e)
            print('training')
            points = self.get_train_points(popsize_range=[100000,100000], selection_coeff_range=[0, 0])
            #points.extend(self.get_train_points(negative=False))
            self.fit_per_selection_linear_regression(points)

    def get_train_points(self, num=100, popsize_range=[4, 500000], negative=True, selection_coeff_range=[0.0001, 0.000001]):
        points = []
        muxpop_range = [0.0001, 0.1]
        selection_coeff_range = [math.log10(s) if s != 0 else 0 for s in selection_coeff_range]
        train_points = []
        for i, muxpop in enumerate(np.linspace(math.log10(muxpop_range[0]), math.log10(muxpop_range[1]), int(math.sqrt(num)))):
            #print(f'---{i}---', end='\r')
            for popsize in np.linspace(popsize_range[0], popsize_range[1], int(math.sqrt(num))):
                muxpop_ = math.pow(10, muxpop)
                mue_frwrd = muxpop_/popsize
                pop_size = popsize

                point = GPA(mue_frwrd, 0, pop_size, selection_coeff=0)
                #point.mean_sub_rate = self.get_sub_rate_diffusion(point)
                points.append(point)

                if selection_coeff_range == [0,0]: continue
                for selection_coeff in np.linspace(selection_coeff_range[0], selection_coeff_range[1], int(math.sqrt(num))):
                    selection_coeff = math.pow(10, selection_coeff) if selection_coeff != 0 else 0
                    if negative: selection_coeff *= -1

                    try:
                        point = GPA(mue_frwrd, 0, pop_size, selection_coeff=selection_coeff)
                        #mean_sub_rate = self.get_sub_rate_diffusion(point)

                        #if mean_sub_rate == np.inf: continue

                        #point.mean_sub_rate = mean_sub_rate
                        points.append(point)
                    except Exception as e:
                        pass
        def sub_rate(point):
            sub = self.get_sub_rate(point)
            if sub == np.inf: return None
            point.mean_sub_rate = sub
            return point

        points = Parallel(n_jobs=-1, verbose=0)(delayed(sub_rate)(point) for point in points)
        points = [point for point in points if point is not None]


        return points

    def fit_per_selection_linear_regression(self, points):
        '''fit a linear regression for each selection coefficient
        '''
        per_selection_points = {}
        pops = [point.pop_size for point in points]
        for pop in pops:
            per_pop_points = {}
            inner_points = [point for point in points if point.pop_size == pop]

            per_selection_points = {}
            for point in inner_points:
                if point.selection_coeff not in per_selection_points:
                    per_selection_points[point.selection_coeff] = []
                per_selection_points[point.selection_coeff].append(point)

            if pop not in per_pop_points: per_pop_points[pop] = {}
            per_pop_points[pop] = per_selection_points

            self.per_pop_linear_regression[pop] = {s: self._fit_linear_regression(per_selection_points[s]) for s in per_selection_points.keys()}
            pickle.dump(self.per_pop_linear_regression, open(f"per_pop_linear_regression.pkl", "wb"))

    def _fit_linear_regression(self, points):
        xs = np.array([np.log10(point.mue_frwrd) for point in points])
        ys = np.array([np.log10(point.mean_sub_rate) for point in points])

        def linear(x, a, b):
            return a*x + b

        popt, pcov = curve_fit(linear, xs, ys)
        return popt

    def get_sub_rate(self, point):

        #if point.mue_frwrd * point.pop_size <= 0.001:
        if point.mue_frwrd * point.pop_size <= 0.00001 and point.pop_size > self.stiching_point:
            #print('regression')
            return self.get_sub_rate_regression(point)

        if point.pop_size < self.stiching_point:
            return self.get_sub_rate_exact(point)
        else:
            try:
                if point.selection_coeff==0:
                    return self.get_sub_rate_diffusion_4_allele_renewal(point) #4 allele model
                    #return self.get_sub_rate_diffusion_beta(point) #2allele model
                else:
                    #return self.get_sub_rate_diffusion(point)
                    return self.get_sub_rate_diffusion_4_allele_renewal(point)
            except Exception as e:
                return np.inf

    def get_sub_rate_regression(self, point, interpolate=True, test=False):
        '''get the sub rate using the linear regression
        '''
        def regression_sub(point, selection=None):
            if selection is None: selection = point.selection_coeff
            a, b = per_selection_linear_regression[selection]
            log_subrate = a*np.log10(point.mue_frwrd) + b
            return 10**log_subrate

        if not self.per_pop_linear_regression:
            raise Exception('fit the linear regression first')

        if point.pop_size not in self.per_pop_linear_regression:
            extra_points = self.get_train_points(num=20, popsize_range=[point.pop_size, point.pop_size], negative=False)
            self.fit_per_selection_linear_regression(extra_points)

        per_selection_linear_regression = self.per_pop_linear_regression[point.pop_size]

        def regression_sub(point, selection=None):
            if selection is None: selection = point.selection_coeff
            a, b = per_selection_linear_regression[selection]
            log_subrate = a*np.log10(point.mue_frwrd) + b
            return 10**log_subrate

        selections = [float(x) for x in per_selection_linear_regression.keys()]

        if test and point.selection_coeff in selections:
            #remove the point from the list
            selections.remove(point.selection_coeff)

        if point.selection_coeff < min(selections): return 0
        elif point.selection_coeff > max(selections): return regression_sub(point, max(selections))
        elif point.selection_coeff in selections: return regression_sub(point)

        if point.selection_coeff not in selections:

            if not interpolate:
                min_diff = np.inf
                for selection in selections:
                    if abs(selection - point.selection_coeff) < min_diff:
                        min_diff = abs(selection - point.selection_coeff)
                        most_similar_selection = selection
                return regression_sub(point, most_similar_selection)

            if point.selection_coeff <= min(selections):
                return regression_sub(point, min(selections))

            elif point.selection_coeff >= max(selections):
                return regression_sub(point, max(selections))

            upper = min([x for x in selections if x > point.selection_coeff])
            lower = max([x for x in selections if x < point.selection_coeff])


            subh = np.log10(regression_sub(point, upper))
            subl = np.log10(regression_sub(point, lower))

            #y = y1 + (x-x1)*(y2-y1)/(x2-x1)
            value = subl + (point.selection_coeff - lower)*(subh-subl)/(upper-lower)

            return 10**value
        
    def get_mu(self, point,sub_matrix,a,b,return_matrix=False):
        """
        solve for mu_a_b simultaneously for a,b in [A,C,G,T]
        calculating from 4 allele diffusion sub rate
        mu matrix is a dict of dicts with keys A,C,G,T and values the mutation rates

        """
        def matrix_to_vector(matrix,index_list=False):
            """
            Convert 4x4 dict-of-dicts to 12-vector of off-diagonal entries.
            Order is:
                A->C, A->G, A->T,
                C->A, C->G, C->T,
                G->A, G->C, G->T,
                T->A, T->C, T->G
            """
            out = []
            indexs=[]
            for a in BASES:
                for b in BASES:
                    if a == b:
                        continue
                    out.append(matrix[a][b])
                    indexs.append((a, b))
            if index_list:
                return np.array(out, dtype=float), indexs
            else:
                return np.array(out, dtype=float)

        def vector_to_matrix(vec):
            """
            Convert 12-vector back to 4x4 dict-of-dicts.
            Diagonal entries are set to 0.
            """
            matrix = {
                a: {b: 0.0 for b in BASES}
                for a in BASES
            }

            i = 0
            for a in BASES:
                for b in BASES:
                    if a == b:
                        continue

                    matrix[a][b] = vec[i]
                    i += 1

            return matrix

        # ------------------------------------------------------------
        # 1. Construct the system of equations
        # ------------------------------------------------------------
        def system(mu_guess_vector, sub_vector):
            
            if (mu_guess_vector <= 0).any() or (mu_guess_vector > 1).any():
                return np.array([1e20]*12)
            try:
                #convert mu_guess to mu_matrix
                # enforce physical domain
                mu_matrix = vector_to_matrix(mu_guess_vector)
                sub_matrix_from_guesss=self.get_sub_rate_diffusion_4_allele_renewal(point, mu_matrix)
                sub_vector_guess=matrix_to_vector(sub_matrix_from_guesss)
                #return errors from each combo
                return sub_vector_guess - sub_vector

            except Exception:
                return np.array([1e20]*12)
            
        sub_vector,index_list=matrix_to_vector(sub_matrix,index_list=True)
        x0=sub_vector #initital guess is sub rate = mu rate
        sol = root(system, x0,  args=(sub_vector,),method='hybr')
        
        if return_matrix:
            return vector_to_matrix(sol.x)
        #extract number of mutation from a->b given the order of the vector
        else:
            idx=index_list.index((a, b))
            return sol.x[idx]



    def get_mu_2_allele(self, point):
        """
        Solve for (mu_f, mu_b) simultaneously by matching the observed 
        forward and backward substitution rates using a robust expanding 
        global search.

        This replaces brittle 1-D root finding and works even when the
        substitution function is undefined or non-monotonic.
        """

        # ------------------------------------------------------------
        # 1. Construct the system of equations
        # ------------------------------------------------------------
        def system(mu_vec):
            mu_f,mu_b = mu_vec
            """Return F1, F2 = (subf - obsf), (subb - obsb)."""
            try:
                gpf = GPA(mu_f, mu_b, 
                         pop_size=point.pop_size,
                         mean_sub_rate=None,
                         selection_coeff=point.selection_coeff)
                subf = self.get_sub_rate(gpf)
                gpb = GPA(mu_b, mu_f, 
                         pop_size=point.pop_size,
                         mean_sub_rate=None,
                         selection_coeff=point.selection_coeff)
                subb = self.get_sub_rate(gpb)

                return subf - point.mean_sub_rate, subb - point.mue_bckwrds
            

            except Exception:
                return np.inf, np.inf
            
        def system(mu_vec):
            mu_f, mu_b = mu_vec

            # enforce physical domain
            if mu_f <= 0 or mu_b <= 0 or mu_f > 1 or mu_b > 1:
                return np.array([1e20, 1e20])

            try:
                gpf = GPA(mu_f, mu_b,
                        pop_size=point.pop_size,
                        selection_coeff=point.selection_coeff)

                gpb = GPA(mu_b, mu_f,
                        pop_size=point.pop_size,
                        selection_coeff=point.selection_coeff)

                subf = self.get_sub_rate(gpf)
                subb = self.get_sub_rate(gpb)

                if not (np.isfinite(subf) and np.isfinite(subb)):
                    return np.array([1e20, 1e20])

                return np.array([
                    subf - point.mean_sub_rate,
                    subb - point.mue_bckwrds
                ])

            except Exception:
                return np.array([1e20, 1e20])
        x0=(point.mean_sub_rate, point.mue_bckwrds)
        sol = root(system, x0, method='hybr')
        
        return sol.x[0]



    #current best function fot get mu solving only for muforward-ass hossams
    def get_mu_scalar(self, point, ratio=0, **kwargs):
        """
        Robustly estimate forward mutation rate (mu) for a given point by matching
        the expected substitution rate. Uses root_scalar instead of binary search
        to handle non-monotonic cases.
        """
        def expected_rate(mu):
            if ratio == 0 and point.mue_bckwrds is not None:
                mu_b = point.mue_bckwrds
            else:
                mu_b = mu / ratio if ratio != 0 else mu

            try:
                rate = self.get_sub_rate(
                    GPA(mu, mu_b, pop_size=point.pop_size, selection_coeff=point.selection_coeff)
                )
                return rate if np.isfinite(rate) else np.inf
            except Exception:
                print(Exception)
                return np.inf

        # Define function for root finding: difference between expected and observed substitution rate
        def func(mu):
            return expected_rate(mu) - point.mean_sub_rate

        # Define search interval
        l_boundary = point.mean_sub_rate *1.01
        r_boundary = point.mean_sub_rate * 0.99

        # Check function values at bounds
        f_left = func(l_boundary)
        f_right = func(r_boundary)

        # If no sign change (bad bracket), expand automatically
        
        
        if np.sign(f_left) == np.sign(f_right) or not np.isfinite(f_left) or not np.isfinite(f_right):
            #print(f"[get_mu] Expanding search range for pop={point.pop_size}, sel={point.selection_coeff}")
            for scale in [1.5,1e2, 1e4, 1e6]:
                l_new = point.mean_sub_rate / scale
                r_new = point.mean_sub_rate * scale
                f_left, f_right = func(l_new), func(r_new)
                print(f_left, f_right)
                if np.sign(f_left) != np.sign(f_right):
                    l_boundary, r_boundary = l_new, r_new
                    break
            else:
                raise Exception("[get_mu] Could not bracket root (function may be monotonic or invalid)")

        # Use robust root finder
        try:
            sol = root_scalar(func, bracket=[l_boundary, r_boundary], method='brentq', xtol=1e-12)
            #checking shape of func
            #xs = np.linspace(l_boundary, r_boundary, 1000)
            #plt.scatter(xs, [func(x) for x in xs])
            #plt.show()
        except Exception as e:
            print(f"[get_mu] Root finding failed: {e}")
            raise Exception("did not converge")

        mu_est = sol.root

        # Sanity check: verify convergence accuracy
        err = abs(func(mu_est))
        if err > 1e-6:
            print(f"[get_mu] Warning: high error ({err}) for pop={point.pop_size}, sel={point.selection_coeff}")
            raise Exception("did not converge")
        
        return mu_est
     

    def get_sub_rate_exact(self, point):
        '''command format: wfes_single --fixation -N [pop_size] -s [selection_coeff] -v [mue_frwrd] -u [mue_bckwrds] -h 0.5
        '''
        command = f'{wfes_single} --fixation -N {point.pop_size} -s {point.selection_coeff*2} \
                    -v {point.mue_frwrd} -u {point.mue_bckwrds} -h 0.5'

        process = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        output = output.decode()
        lines = output.split('\n')
        time = np.inf
        for line in lines:
            if 'T_fix' in line:
                time = float(line.split('=')[1].strip())
        if time == np.inf:
            return np.inf
        return 1/(time)

    def get_sub_rate_diffusion(self,point):
        """
        Compute the substitution rate k for a Wright-Fisher diffusion
        with selection and two-way mutation.
        as sub rate = 1/time to fixation in generations
        assuming mut starts at freq 1/2N and left boundary loss is refexive


        Parameters
        ----------
        N : int
            Diploid population size.
        mu_f : float
            Forward mutation rate.
        mu_b : float
            Backward mutation rate.
        s : float
            Selection coefficient.

        Returns
        -------
        k : float
            Substitution rate.
        """
        # Scaled parameters
        sigma = 2*point.pop_size*point.selection_coeff
        u1 = 2*point.mue_frwrd*point.pop_size
        u2 = 2*point.mue_bckwrds*point.pop_size
        N=point.pop_size
        x0=0
        #x0 = 1/(2*N)

        # Auxiliary function psi
        def psi(y):
            # avoid division by zero at boundaries
            y = np.clip(y, 1e-12, 1-1e-12)
            return np.exp(-2 * sigma * y) * (y**(-2*u1)) * ((1-y)**(-2*u2))

        # Normalization constant for scale function
        C, _ = I(psi, 0, 1)

        # Scale function phi -not using as presimplified
        def phi(x):
            integral, _ = I(psi, 0, x)
            return integral / C

        def x_1_psi(x):
            integral, _ = I(psi, x, 1)
            return integral

        #no reflection 
        def g(y):
            if y < x0:
                return 2* x_1_psi(x0) / (y * (1 - y) * psi(y))
            else:
                return 2* x_1_psi(y) / (y * (1 - y) * psi(y))

        #time to fixation from zero-allowing loss then new muts
        T_abs_star, _ = I(g, 0, 1)
        
        #mut rate = 1/time in generations
        k=1/(2*N*T_abs_star) 
        

        return k

    #efficent calc of sub rate when no selection, using beta functions
    def get_sub_rate_diffusion_beta(self,point):
        u1 = 2*point.mue_frwrd*point.pop_size
        u2 = 2*point.mue_bckwrds*point.pop_size
        N=point.pop_size
        a = 1 - 2*u1
        b = 1 - 2*u2
        B_ab = beta(a, b)

    # integrand for alpha(0) (with 2*B_ab pullled out as constants)
        def integrand(y):
            return ((1 - betainc(a, b, y)) *
                    y**(2*u1 - 1) *
                    (1 - y)**(2*u2 - 1))

        alpha0, _ = I(integrand, 0, 1, epsabs=1e-8, epsrel=1e-8)

        return 1.0 / (4 * N * B_ab * alpha0)
    
    def get_sub_rate_diffusion_4_allele_renewal_slow(self, point, mu_matrix,alleles=("A", "C", "G", "T"),all_rates=True,a=None, b=None):
        '''
        was trying to derive by changing mean time to path
        but understimating, as not account for ossibility from sub to other allele then to sub of interet, also O(mu)'''
        
        # caching to increase speed
        # Scope the cache to the current population size so it doesn't grow
        # unbounded across many different N guesses (e.g. brute-force search).
        if (not hasattr(self, "_diffusion_cache")) or (self._diffusion_cache.get("pop_size") != getattr(point, "pop_size", None)):
            self._diffusion_cache = {
                "pop_size": getattr(point, "pop_size", None),
                "den": {},
                "phi": {},
                "phi_prime": {},
                "alpha": {},
                "denominator": {},
            }

        cache = self._diffusion_cache

        def cache_key(*vals):
            return tuple(round(float(v), 16) for v in vals)


        # inner functions
        def get_mu(x, y):
            """
            Per-generation mutation rate x -> y.
            
            """
            
            return mu_matrix[x][y]

        def get_s(x):
            """
            Allele fitness/selection value.
            Edit this line if your selection coefficients are stored differently.
            """
            if hasattr(point, "selection"):
                return 
            return 0.0

        def psi(mu, sigma, u1, u2):
            """
            ψ(μ) = exp(-2 σ μ) * μ^{-2u1} * (1-μ)^{-2u2}
            """
            # Avoid singularities at endpoints
            if mu <= 0.0:
                return 0.0
            if mu >= 1.0:
                return 0.0

            return (
                np.exp(-2.0 * sigma * mu)
                * (mu ** (-2.0 * u1))
                * ((1.0 - mu) ** (-2.0 * u2))
            )

        def psi_den(sigma, u1, u2):
            """
            Cached denominator ∫0^1 ψ(μ)dμ.
            """
            key = cache_key(sigma, u1, u2)

            if key not in cache["den"]:
                den, _ = I(psi, 0.0, 1.0, args=(sigma, u1, u2))
                cache["den"][key] = den

            return cache["den"][key]
        
        def phi(x, sigma, u1, u2):
            """
            Cached φ(x) = ∫0^x ψ(μ)dμ / ∫0^1 ψ(μ)dμ.
            """
            key = cache_key(x, sigma, u1, u2)

            if key not in cache["phi"]:
                if x <= 0.0:
                    cache["phi"][key] = 0.0
                elif x >= 1.0:
                    cache["phi"][key] = 1.0
                else:
                    num, _ = I(psi, 0.0, x, args=(sigma, u1, u2))
                    den = psi_den(sigma, u1, u2)
                    cache["phi"][key] = num / den

            return cache["phi"][key]
        
        def prob_not_x(mu_xb,mu_ab):
            '''E(rate b|X mut freq 1/2N) - samll correction term for 3 alleles
            while x lineage is rising or fixing can get second mutation withewr x->b or a->b
            assume second mutation has prob 1/2N of fixing
            rate of supply muts, given x has vaf xt is
            M mu_xb M x_t+M mu_ab M (1-x_t)
            Then take expectation over t
            gives expected rate of supply, then multiply by pfix 1/M
            '''

            # raw supply would be M**2 * (...).
            # multiply by p_fix = 1/M, giving M * (...).
            p_xb=-2*M*mu_xb*(1-1/(2*N))*math.log((1-1/(2*N)))
            p_ab=-2*M*mu_ab*(1/(2*N))*math.log(1/(2*N))
            
            return p_xb+p_ab

        def phi_prime(x, sigma, u1, u2):
            """
            Cached φ'(x) = ψ(x) / ∫0^1 ψ(μ)dμ.
            """
            key = cache_key(x, sigma, u1, u2)

            if key not in cache["phi_prime"]:
                den = psi_den(sigma, u1, u2)
                cache["phi_prime"][key] = psi(x, sigma, u1, u2) / den

            return cache["phi_prime"][key]

        def green(x, y, sigma, u1, u2):
            """
            Killed Green function for absorption at 0 or 1. Starting at x
            """
            if y <= 0.0 or y >= 1.0:
                return 0.0

            g2 = y * (1.0 - y)
            phix = phi(x, sigma, u1, u2)
            phiy = phi(y, sigma, u1, u2)
            phipy = phi_prime(y, sigma, u1, u2)

            if x < y:
                return 2.0 * phix * (1.0 - phiy) / (g2 * phipy)
            else:
                return 2.0 * (1.0 - phix) * phiy / (g2 * phipy)

        def alpha(x, sigma, u1, u2):
            """
            Cached α(x) = ∫0^1 G(x,y)dy.
            Mean absorption time in diffusion units.
            """
            key = cache_key(x, sigma, u1, u2)

            if key not in cache["alpha"]:
                eps = 1e-12

                left = 0.0
                right = 0.0

                if x > eps:
                    left, _ = I(
                        lambda y: green(x, y, sigma, u1, u2),
                        eps,
                        x,
                    )

                if x < 1.0 - eps:
                    right, _ = I(
                        lambda y: green(x, y, sigma, u1, u2),
                        x,
                        1.0 - eps,
                    )

                cache["alpha"][key] = left + right

            return cache["alpha"][key]

        def neutral_alpha(x):
            """
            Neutral mean time to loss or fixation in diffusion units.
            Generator: 0.5 * x * (1-x) * f''(x)
            """
            if x <= 0.0 or x >= 1.0:
                return 0.0

            return -2.0 * (
                x * np.log(x) +
                (1.0 - x) * np.log1p(-x)
            )

        def edge_params(x, y):
            """
            Parameters for edge x -> y.
            Coordinate is frequency of y:
                0 = fixed x
                1 = fixed y
            """
            mu_xy = get_mu(x, y)
            mu_yx = get_mu(y, x)

            theta_xy = M * mu_xy
            theta_yx = M * mu_yx

            sigma_xy = M * (get_s(y) - get_s(x))

            return theta_xy, theta_yx, sigma_xy
        
        def get_outward_rate(x):
            rate=0
            for y in alleles:
                if x==y: continue
                rate+=get_mu(x,y)
            return rate


        
        def calc_rate(a,b):
            # numerator: theta_ab * phi_ab(1/M)
            theta_ab, theta_ba, sigma_ab = edge_params(a, b)

            if theta_ab <= 0.0:
                return 0.0

            #only allow first order mutations
            #prob of fixation
            phi_ab_x0 = phi(x0, sigma_ab, theta_ab, M*get_outward_rate(b))

            
            # denominator: 1 + M * sum_{c != a} theta_ac * alpha_ac(1/M)
            denominator_extra = 0.0
            lambda_a=0
            for c in alleles:
                if c == a:
                    continue

                theta_ac, theta_ca, sigma_ac = edge_params(a, c)
                if c==b:
                    #then can use full expected time to loss or fixation
                    if theta_ac <= 0.0:continue
                    alpha_ac_x0 = alpha(x0, sigma_ac, theta_ac, M*get_outward_rate(c))
                    denominator_extra += theta_ac * alpha_ac_x0
                    continue
                #else approximate with standard time to fixation
                lambda_a+=theta_ac
                #using outward_c will over inflate rate of extinction->denomenator larger
                #alpha_ac_x0 = alpha(x0, sigma_ac, theta_ac, theta_ca)
                #alpha_ac_x0 = alpha(x0, sigma_ac, theta_ac, get_outward_rate(c))
                #alpha_ac_x0 = alpha(x0, sigma_ac, 0, 0)
                
                alpha_ac_x0=neutral_alpha(x0)
                #print(theta_ac)
                
                denominator_extra += theta_ac * alpha_ac_x0

            numerator = theta_ab * phi_ab_x0
            
            #prob of fixation of b given first mutation not to b
            for j in alleles:
                if a==j: continue
                if b==j: continue
                #M*get_mu(a,j)*
                #mut supply N*muaj *prob of fixation
                prob=M*get_mu(a,j)*prob_not_x(get_mu(j,b),get_mu(a,b))
                
                numerator+=prob

            #numerator = lambda_a * phi_ab_x0


            Qedge_ab = numerator / (1.0 + M * denominator_extra)

            return Qedge_ab
        
        N = point.pop_size
        M = 2.0 * N
        x0 = 1.0 / M
        if not all_rates:
            return calc_rate(a,b)
        else:
            Qedge = {
                x: {y: 0.0 for y in alleles}
                for x in alleles
            }

            for x in alleles:
                for y in alleles:
                    if x == y:
                        Qedge[x][y] = 0.0
                    else:
                        Qedge[x][y] = calc_rate(x, y)

            #for x in alleles:
                #Qedge[x][x] = -sum(Qedge[x][y] for y in alleles if y != x)

            return Qedge
        

        
    def get_sub_rate_diffusion_4_allele_renewal(self, point, mu_matrix,alleles=("A", "C", "G", "T"),all_rates=True,a=None, b=None):
        
        '''
        O(mu) approximation to 4 allele mutation rates
        input:mu_matrix=dict of dicts {ref:{alt:x}}'''
        #pre calculations to inc speed
        N = point.pop_size
        M = 2.0 * N
        x0 = 1.0 / M

        # Precompute mutation matrix and scaled mutation matrix

        

        theta_lookup = {
            x: {y: M * mu_matrix[x][y] for y in alleles}
            for x in alleles
        }

        outward_rate = {
            x: sum(mu_matrix[x][y] for y in alleles if y != x)
            for x in alleles
        }

        outward_theta = {
            x: M * outward_rate[x]
            for x in alleles
        }

        neutral_alpha_x0 = -2.0 * (
            x0 * np.log(x0)
            + (1.0 - x0) * np.log1p(-x0)
        )

        # occupation time of intermediate lineage
        occ_x = -2.0 * (1.0 - x0) * np.log1p(-x0)

        # occupation time of ancestral background
        occ_a = -2.0 * x0 * np.log(x0)
        
        
        def get_mu(x, y):
            return mu_matrix[x][y]


        def get_theta(x, y):
            return theta_lookup[x][y]




        def get_outward_theta(x):
            return outward_theta[x]
        # caching to increase speed
        # Scope the cache to the current population size so it doesn't grow
        # unbounded across many different N guesses (e.g. brute-force search).
        if (not hasattr(self, "_diffusion_cache")) or (self._diffusion_cache.get("pop_size") != getattr(point, "pop_size", None)):
            self._diffusion_cache = {
                "pop_size": getattr(point, "pop_size", None),
                "den": {},
                "phi": {},
                "phi_prime": {},
                "alpha": {},
                "denominator": {},
            }

        cache = self._diffusion_cache

        def cache_key(*vals):
            return tuple(round(float(v), 16) for v in vals)


        

        def get_s(x):
            """
            Allele fitness/selection value.
            Edit this line if your selection coefficients are stored differently.
            """
            
            return 0.0

        
        def phi(x, sigma, u1, u2):
            """
            Cached beta-form φ(x), valid for sigma = 0.
            """
            key = cache_key(x, u1, u2)

            if key not in cache["phi"]:
                if x <= 0.0:
                    cache["phi"][key] = 0.0
                elif x >= 1.0:
                    cache["phi"][key] = 1.0
                else:
                    aa = 1.0 - 2.0 * u1
                    bb = 1.0 - 2.0 * u2

                    if aa <= 0.0 or bb <= 0.0:
                        cache["phi"][key] = np.nan
                    else:
                        cache["phi"][key] = betainc(aa, bb, x)

            return cache["phi"][key]
        
       
            
        def prob_not_x(mu_xb, mu_ab):
            """
            Expected number of second mutations to b that arise during a neutral
            a/x segregating episode and eventually fix.

            raw supply is M**2 * (...), then multiply by p_fix = 1/M,
            giving M * (...).
            """

            '''E(rate b|X mut freq 1/2N) - samll correction term for 3 alleles
            while x lineage is rising or fixing can get second mutation withewr x->b or a->b
            assume second mutation has prob 1/2N of fixing
            rate of supply muts, given x has vaf xt is
            M mu_xb M x_t+M mu_ab M (1-x_t)
            Then take expectation over t
            gives expected rate of supply, then multiply by pfix 1/M
            

            # raw supply would be M**2 * (...).
            # multiply by p_fix = 1/M, giving M * (...).
            p_xb=-2*M*mu_xb*(1-1/(2*N))*math.log((1-1/(2*N)))
            p_ab=-2*M*mu_ab*(1/(2*N))*math.log(1/(2*N))
            
            return p_xb+p_ab
            '''

            return M * (
                mu_xb * occ_x
                + mu_ab * occ_a
            )

        

        def alpha(x, sigma, u1, u2):
            """
            Cached α(x) = ∫0^1 G(x,y)dy.
            greens function with backward mutations killing at 0,1

            Beta-form version, valid for sigma = 0.
            """
            key = cache_key(x, u1, u2)

            if key not in cache["alpha"]:

                # neutral shortcut
                if abs(u1) < 1e-15 and abs(u2) < 1e-15:
                    cache["alpha"][key] = neutral_alpha_x0
                    return cache["alpha"][key]

                aa = 1.0 - 2.0 * u1
                bb = 1.0 - 2.0 * u2

                if aa <= 0.0 or bb <= 0.0:
                    cache["alpha"][key] = np.nan
                    return cache["alpha"][key]

                beta_ab = beta(aa, bb)
                Ix = betainc(aa, bb, x)

                eps = 1e-12

                def denom(y):
                    return (
                        y * (1.0 - y)
                        * (y ** (-2.0 * u1))
                        * ((1.0 - y) ** (-2.0 * u2))
                    )

                def green_left(y):
                    Iy = betainc(aa, bb, y)
                    return 2.0 * beta_ab * Iy * (1.0 - Ix) / denom(y)

                def green_right(y):
                    Iy = betainc(aa, bb, y)
                    return 2.0 * beta_ab * Ix * (1.0 - Iy) / denom(y)

                left = 0.0
                right = 0.0

                if x > eps:
                    left, _ = I(
                        green_left,
                        eps,
                        x,
                        epsabs=1e-9,
                        epsrel=1e-7,
                        limit=100,
                    )

                if x < 1.0 - eps:
                    right, _ = I(
                        green_right,
                        x,
                        1.0 - eps,
                        epsabs=1e-9,
                        epsrel=1e-7,
                        limit=100,
                    )

                cache["alpha"][key] = left + right

            return cache["alpha"][key]

        def neutral_alpha(x):
            """
            Neutral mean time to loss or fixation in diffusion units.
            Generator: 0.5 * x * (1-x) * f''(x)
            """
            if x <= 0.0 or x >= 1.0:
                return 0.0

            return -2.0 * (
                x * np.log(x) +
                (1.0 - x) * np.log1p(-x)
            )

        


        def calc_rate(a, b):
            theta_ab = get_theta(a, b)

            if theta_ab <= 0.0:
                return 0.0

            # beta version assumes sigma = 0
            sigma_ab = 0.0

            phi_ab_x0 = phi(
                x0,
                sigma_ab,
                theta_ab,
                get_outward_theta(b)
            )

            numerator = theta_ab * phi_ab_x0

            denominator_extra = 0.0

            for c in alleles:
                if c == a:
                    continue

                theta_ac = get_theta(a, c)

                if theta_ac <= 0.0:
                    continue

                if c == b:
                    alpha_ac_x0 = alpha(
                        x0,
                        0.0,
                        theta_ac,
                        get_outward_theta(c)
                    )
                else:
                    alpha_ac_x0 = neutral_alpha_x0

                denominator_extra += theta_ac * alpha_ac_x0

            # second-order prob of fixation through intermediate allele correction
            for j in alleles:
                if j == a:
                    continue
                if j == b:
                    continue

                numerator += get_theta(a, j) * prob_not_x(
                    get_mu(j, b),
                    get_mu(a, b)
                )

            Qedge_ab = numerator / (1.0 + M * denominator_extra)

            return Qedge_ab
        
        N = point.pop_size
        M = 2.0 * N
        x0 = 1.0 / M
        if not all_rates:
            return calc_rate(a,b)
        else:
            Qedge = {
                x: {y: 0.0 for y in alleles}
                for x in alleles
            }

            for x in alleles:
                for y in alleles:
                    if x == y:
                        Qedge[x][y] = 0.0
                    else:
                        Qedge[x][y] = calc_rate(x, y)

            #for x in alleles:
                #Qedge[x][x] = -sum(Qedge[x][y] for y in alleles if y != x)

            return Qedge
        
    def get_sub_rate_diffusion_prob_hit(self, point):
        # inner functions
        def psi(mu, sigma, u1, u2):
            """
            ψ(μ) = exp(-2 σ μ) * μ^{-2u1} * (1-μ)^{-2u2}
            """
            # Avoid singularities at endpoints
            if mu <= 0.0:
                return 0.0
            if mu >= 1.0:
                return 0.0

            return (
                np.exp(-2.0 * sigma * mu)
                * (mu ** (-2.0 * u1))
                * ((1.0 - mu) ** (-2.0 * u2))
            )

        def phi(x, sigma, u1, u2):
            """
            φ(x) = ∫0^x ψ(μ)dμ / ∫0^1 ψ(μ)dμ
            """
            num, _ = I(psi, 0.0, x, args=(sigma, u1, u2))
            den, _ = I(psi, 0.0, 1.0, args=(sigma, u1, u2))
            return num / den

        def phi_prime(x, sigma, u1, u2):
            """
            φ'(x) = ψ(x) / ∫0^1 ψ(μ)dμ
            """
            den, _ = I(psi, 0.0, 1.0, args=(sigma, u1, u2))
            return psi(x, sigma, u1, u2) / den

        def green(x, y, sigma, u1, u2):
            """
            Killed Green function for absorption at 0 or 1. 
            """
            if y <= 0.0 or y >= 1.0:
                return 0.0

            g2 = y * (1.0 - y)
            phix = phi(x, sigma, u1, u2)
            phiy = phi(y, sigma, u1, u2)
            phipy = phi_prime(y, sigma, u1, u2)

            if x < y:
                return 2.0 * phix * (1.0 - phiy) / (g2 * phipy)
            else:
                return 2.0 * (1.0 - phix) * phiy / (g2 * phipy)

        def alpha(x, sigma, u1, u2):
            """
            α(x) = ∫0^1 G(x,y)dy
            Mean absorption time in diffusion units.
            """
            eps = 1e-12

            left, _ = I(
                lambda y: green(x, y, sigma, u1, u2),
                eps,
                x,
            )

            right, _ = I(
                lambda y: green(x, y, sigma, u1, u2),
                x,
                1.0 - eps,
            )

            return left + right

        mu_f = point.mue_frwrd
        mu_b = point.mue_bckwrds
        N = point.pop_size

        M = 2.0 * N

        sigma = M * point.selection_coeff
        u1 = M * mu_f
        u2 = M * mu_b

        x0 = 1.0 / M

        phi_x0 = phi(x0, sigma, u1, u2)
        alpha_x0 = alpha(x0, sigma, u1, u2)

        # Mean waiting time for first mutation in generations:
        # 1 / (M * mu_f)
        #
        # Mean segregating time in generations:
        # M * alpha_x0
        #
        # Substitution rate per generation:
        sub_rate = phi_x0 / ((1.0 / (M * mu_f)) + (M * alpha_x0))
        return sub_rate
            
    
    
       
    def get_selection(self, sub_rate, mu, pop_size, ratio=1, l_boundary=1e-4, r_boundary=1e-6, negative=True):
        '''gradient descent to find the selection that gives the sub_rate
        '''

        @np.vectorize
        def error(selection):
            expected_sub_rate = self.get_sub_rate(GPA(mu, mu*ratio, pop_size, selection))
            if expected_sub_rate is None: return np.inf
            '''if log10(expected_sub_rate / sub_rate) < -100:
                bla = 1'''
            e = expected_sub_rate / sub_rate
            e = abs(1-e)
            if e == 1: return np.inf
            return e
            #return (self.get_sub_rate(GPA(mu, mu*ratio, pop_size, selection)) - sub_rate)**2

        res = self.minimize_by_search(error, [l_boundary,r_boundary], negative=negative)
        return res

    def binary_search(self, func, bounds, search_parameter,
                      tol=10**-10, depth=0, negative=True,
                      max_depth=25, log=True, left=None, right=None, **kwargs):

        if depth == 0:
            left = func(bounds[0], **kwargs) if not negative else func(-bounds[0], **kwargs)
            right = func(bounds[1], **kwargs) if not negative else func(-bounds[1], **kwargs)

        middle = (bounds[0] + bounds[1])/2 if not log else 10**((log10(bounds[0]) + log10(bounds[1]))/2)
        middle = -middle if negative else middle
        middle_value = func(middle, **kwargs)
        if abs(middle_value - search_parameter) <= tol:
            return middle

        if depth > max_depth:
            #print('did not converge, minimum error is', abs(middle_value - search_parameter))
            raise Exception('did not converge')
            return middle
        if left< search_parameter < middle_value:
            return self.binary_search(func, [bounds[0], abs(middle)], search_parameter, tol=tol,
                                      depth=depth+1, negative=negative, max_depth=max_depth,
                                      log=log, left=left, right=middle_value, **kwargs)
        elif middle_value < search_parameter < right:
            return self.binary_search(func, [abs(middle), bounds[1]], search_parameter, tol=tol,
                                      depth=depth+1, negative=negative, max_depth=max_depth,
                                      log=log, left=middle_value, right=right, **kwargs)
        else:
            #print('did not converge, minimum error is', abs(middle_value - search_parameter))
            raise Exception('did not converge')
            return middle

    def minimize_by_search(self, func, bounds, tol=10**-10,
                           depth=0, negative=True, breadth=10, first_breadth=None,
                           max_depth=25, nearest_value_tie_breaker=None,
                           log=True, parallel=True,previuos_results={},
                           precesion=0, old_xs=[], old_ys=[],silent=False,**kwargs):
        ''' tolerance is the minimum error that is acceptable
            precesion is the acceptable difference between the bounds

            returns the x that gives the minimum y, and all the computed points
        '''
        def inner_func(x, **kwargs):
            if x in previuos_results:
                return previuos_results[x]
            else:
                return func(x, **kwargs)

        inner_breadth = breadth
        if (depth == 0) and first_breadth is not None: inner_breadth = first_breadth

        if parallel: parallel=-1
        else: parallel=1
        if log:
            xs = np.linspace(log10(abs(bounds[0])), log10(abs(bounds[1])), inner_breadth)
            xs = 10**xs
        else:
            xs = np.linspace(abs(bounds[0]), abs(bounds[1]), inner_breadth)
        if negative: xs = -xs

        xs = np.array([x for x in xs if not np.isnan(x)])
        xs = sorted(xs)

        ys = Parallel(n_jobs=parallel, verbose=0)(delayed(inner_func)(x, **kwargs) for x in xs)
        previuos_results = {x:y for x,y in zip(xs, ys)}
        #ys = [func(x, **kwargs) for x in xs]
        #check if there is more than one minimum
        if nearest_value_tie_breaker is not None:
            minimas = [i for i in range(len(ys)) if ys[i] == min(ys)]
            minimum_i = minimas[np.argmin([abs(xs[i]-nearest_value_tie_breaker) for i in minimas])]
            x = xs[minimum_i]

        else:
            x = xs[np.argmin(ys)]
            minimum_i = np.argmin(ys)

        old_xs.extend(xs)
        old_ys.extend(ys)

        if min(ys) <= tol:
            return x, [old_xs, old_ys]
        if abs(abs(min(xs)) - abs(max(xs))) <= precesion:
            return x, [old_xs, old_ys]
        if len(set(ys)) == 1:
            return x, [old_xs, old_ys]
        if depth > max_depth:
            return x, [old_xs, old_ys]

        if minimum_i == 0:
            l_boundary = xs[0]
            r_boundary = xs[1]
        else:
            new_lower = minimum_i - 1 if minimum_i - 1 >= 0 else 0
            new_upper = minimum_i + 1 if minimum_i + 1 < len(xs) else - 1
            l_boundary = xs[new_lower]
            r_boundary = xs[new_upper]
        if not silent: print('Searching between l_boundary:', l_boundary, 'r_boundary:', r_boundary)
        return self.minimize_by_search(func, [l_boundary, r_boundary], tol, depth=depth+1,
                                       negative=negative, breadth=breadth, max_depth=max_depth,
                                       nearest_value_tie_breaker=nearest_value_tie_breaker,
                                       parallel=parallel, log=log,
                                       previuos_results=previuos_results,
                                       precesion=precesion, old_xs=old_xs, old_ys=old_ys,
                                       silent=silent,**kwargs)
